### PR TITLE
changed cocoapod to xcframework in order to allow for ARM64 builds

### PR DESCRIPTION
**Pull request by cjohn001**
Hello @shiv19 ,
these are the required changes as discussed yesterday. Your explanation worked out of the box, thanks a lot!

### CODE REVIEW

**Comment by shiv19** [comment]
Hey @cjohn001 thanks for this! 😃
I'll release it tomorrow :)

**Comment by shiv19** [comment]
Hey @cjohn001 
Currently none of the demo charts in the ui-charts plugin are working on iOS, after merging your PR. I'll see what's going on
(on the vanilla demo)

For the Angular demo, except the first demo (line chart) none of the other demos are working

All the demos are working correctly when I revert your changes

**Comment by cjohn001** [comment]
@shiv19 : This is bad. I tried both demos, vanilla and angular. They were both working for me. I am currently working with the sources of the PR on a ARM64 MB and they work for me. I have unfortunately given away my old intel macbook. Could you maybe have a look what is broken?

**Comment by shiv19** [comment]
I don't get any errors in the console,
Instead the demo app just crashes if I try to open one of the chart pages.
I've reverted your commit on my local,
And updated the charts demo to ns8.
I'll also try updating ios to use xcframework and see what happens.

**Comment by cjohn001** [comment]
@shiv19: I just have rebuild the plugin and angular-ios demo. Works fine on device and ios simulator. Would be great if you could check why it breaks. The only change I made to the plugin, I copied the framework in version 8.2.2 into the platforms folder. I did not change anything on the framework files. As it runs here on ARM64 might there be some project configuration required for INTEL processors?

**Comment by cjohn001** [comment]
@shiv19: I just asked a friend to build the demo. He told me that he observed the app crashing on an iphone 11 simulator. On an iPhone 15 simulator things were working alright for him. Is this a repeatable behavior for you as well?

**Pull request merged**
