### PR TITLE
Angular

### PR DESCRIPTION
**Pull request by cjohn001**
@shiv19 
This PR fixes issue 28. I updated the Angular bindings. One can now use the old or the new interface. I also updated the demo to show how things work. A lot easier to use now and no timing related trouble anymore. I at the same time update the ios podfile to the lates 8 version of the library

### CODE REVIEW

**Comment by shiv19** [comment]
Thank you @cjohn001 <3

**Comment by shiv19** [comment]
@cjohn001 
can you please rebase your branch with master and push again?

This PR has many commits by me, making it hard to review the actual changes

**Comment by cjohn001** [comment]
I am not so good with git. How does this rebase work?

**Comment by shiv19** [comment]
Also before we do that,
why is this PR coming to the angular branch?

can you please close this PR and make a PR to master branch instead?

from your local branch, just do

git remote add upstream https://github.com/NativeScript/nativescript-ui-charts.git

then

git rebase upstream master

If any rebase conflicts arise
resolve conflicts if any, track the changes (git add .) and run `git rebase --continue`

once the rebase is complete, force push to origin,

`git push origin angular --force`

then make a PR from your angular branch to the master of this repo.

Hope that makes sense.

**Comment by cjohn001** [comment]
@shiv19. I have read your comment to late. But thanks for the explantion.  I did it in a similar way now. Did this work as you meant or should I try again?

**Comment by shiv19** [comment]
Already merged and released your new PR :)
Cheers!
Closing this now.

**Pull request closed without merging**
